package com.geometric.grafico;

import com.geometric.analisis.CargaArchivo;
import com.geometric.excepciones.Errores;
import com.geometric.grafico.Reportes.ErroresT;
import com.geometric.grafico.Reportes.Operaciones;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author vicente
 */
public class Principal extends javax.swing.JFrame {
    
    private Operaciones panelReportes;
    private ErroresT panelErrores;
    private Home home;
    private CargaArchivo cargaArchivo;

    private static Principal instance;

    private PanelDibujo panelDibujo;
    private ArrayList<Figura> figuras;
    private Figura ultimaFigura;
    
    int xMouse, yMouse;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        panelEntrada.setLayout(new BorderLayout());
        panelDibujo = new PanelDibujo();
        panelEntrada.add(panelDibujo, BorderLayout.CENTER);
        figuras = new ArrayList<>();
        panelReportes = new Operaciones();
        panelErrores = new ErroresT();
        home = new Home();
        cargaArchivo = new CargaArchivo();
        
    }
    
    
    public static Principal getInstance() {
        if (instance == null) {
            instance = new Principal();
        }
        return instance;
    }
    
     public ArrayList<Figura> getFiguras() {
        return figuras;
    }

    public void agregarFigura(Figura figura) {
        figuras.add(figura); 
        this.ultimaFigura = figura;  
        panelDibujo.agregarFigura(figura);
        System.out.println("Última figura agregada: " + ultimaFigura);
    }

    public Figura getUltimaFigura() {
        System.out.println("Obteniendo última figura: " + this.ultimaFigura);
        return this.ultimaFigura;
    }
    
    public Operaciones getPanelReportes() {
        return panelReportes;
    }
    
    public ErroresT getPanelErrores(){
        return panelErrores;
    }

    public void agregarFiguraAlReporte(String figura, String color) {
        panelReportes = getPanelReportes();
        panelReportes.agregarFigura(figura);
        panelReportes.agregarColor(color);
    }
    
    public void agregarAnimacionAlReporte(String tipoAnimacion){
        panelReportes = getPanelReportes();
        panelReportes.agregarAnimacion(tipoAnimacion);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEntrada = new javax.swing.JPanel();
        jpanelMenu = new javax.swing.JPanel();
        btnHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEmpezar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelStart = new javax.swing.JLabel();
        jLabelLocation = new javax.swing.JLabel();
        btnReporteOperacion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelStart1 = new javax.swing.JLabel();
        jlabelICONO = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnErroresLS = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabelStart2 = new javax.swing.JLabel();
        panelCabeza = new javax.swing.JPanel();
        jPanelCerrar = new javax.swing.JPanel();
        LabelExit = new javax.swing.JLabel();
        jLabelArchivoEntrada = new javax.swing.JLabel();
        jLabelArchivoEntradaTrafico = new javax.swing.JLabel();
        jPanelContent = new javax.swing.JPanel();
        labelEntrada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        panelEntrada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelMenu.setBackground(new java.awt.Color(20, 34, 41));
        jpanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setBackground(new java.awt.Color(82, 129, 137));
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HOME");

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHomeLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        jpanelMenu.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 270, 70));

        btnEmpezar.setBackground(new java.awt.Color(82, 129, 137));
        btnEmpezar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpezar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmpezarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpezarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmpezarMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VISUALIZAR");

        jLabelStart.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout btnEmpezarLayout = new javax.swing.GroupLayout(btnEmpezar);
        btnEmpezar.setLayout(btnEmpezarLayout);
        btnEmpezarLayout.setHorizontalGroup(
            btnEmpezarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEmpezarLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabelStart, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(75, 75, 75))
        );
        btnEmpezarLayout.setVerticalGroup(
            btnEmpezarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEmpezarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(btnEmpezarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelStart, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jpanelMenu.add(btnEmpezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 270, 70));
        jpanelMenu.add(jLabelLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 40, 40));

        btnReporteOperacion.setBackground(new java.awt.Color(82, 129, 137));
        btnReporteOperacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporteOperacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReporteOperacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReporteOperacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporteOperacionMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REPORTES");

        jLabelStart1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout btnReporteOperacionLayout = new javax.swing.GroupLayout(btnReporteOperacion);
        btnReporteOperacion.setLayout(btnReporteOperacionLayout);
        btnReporteOperacionLayout.setHorizontalGroup(
            btnReporteOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnReporteOperacionLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabelStart1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(84, 84, 84))
        );
        btnReporteOperacionLayout.setVerticalGroup(
            btnReporteOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReporteOperacionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(btnReporteOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelStart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jpanelMenu.add(btnReporteOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 270, -1));

        jlabelICONO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconoIMG.jpg"))); // NOI18N
        jlabelICONO.setText("jLabel4");
        jpanelMenu.add(jlabelICONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(-470, -150, 740, 290));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("©VM325");
        jpanelMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 100, 30));

        btnErroresLS.setBackground(new java.awt.Color(82, 129, 137));
        btnErroresLS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnErroresLS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnErroresLSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnErroresLSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnErroresLSMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ERRORES");

        jLabelStart2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout btnErroresLSLayout = new javax.swing.GroupLayout(btnErroresLS);
        btnErroresLS.setLayout(btnErroresLSLayout);
        btnErroresLSLayout.setHorizontalGroup(
            btnErroresLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnErroresLSLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabelStart2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(84, 84, 84))
        );
        btnErroresLSLayout.setVerticalGroup(
            btnErroresLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnErroresLSLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(btnErroresLSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelStart2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jpanelMenu.add(btnErroresLS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 270, -1));

        panelEntrada.add(jpanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 610));

        panelCabeza.setBackground(new java.awt.Color(20, 34, 41));
        panelCabeza.setForeground(new java.awt.Color(255, 255, 255));
        panelCabeza.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelCabezaMouseDragged(evt);
            }
        });
        panelCabeza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCabezaMousePressed(evt);
            }
        });

        jPanelCerrar.setBackground(new java.awt.Color(158, 189, 203));
        jPanelCerrar.setForeground(new java.awt.Color(0, 0, 0));
        jPanelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseExited(evt);
            }
        });

        LabelExit.setBackground(new java.awt.Color(158, 189, 203));
        LabelExit.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        LabelExit.setText("  X");
        LabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCerrarLayout = new javax.swing.GroupLayout(jPanelCerrar);
        jPanelCerrar.setLayout(jPanelCerrarLayout);
        jPanelCerrarLayout.setHorizontalGroup(
            jPanelCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCerrarLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(LabelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCerrarLayout.setVerticalGroup(
            jPanelCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LabelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabelArchivoEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelArchivoEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelArchivoEntradaMouseClicked(evt);
            }
        });

        jLabelArchivoEntradaTrafico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelCabezaLayout = new javax.swing.GroupLayout(panelCabeza);
        panelCabeza.setLayout(panelCabezaLayout);
        panelCabezaLayout.setHorizontalGroup(
            panelCabezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabezaLayout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(jLabelArchivoEntrada)
                .addGap(18, 18, 18)
                .addComponent(jLabelArchivoEntradaTrafico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 832, Short.MAX_VALUE)
                .addComponent(jPanelCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelCabezaLayout.setVerticalGroup(
            panelCabezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabezaLayout.createSequentialGroup()
                .addGroup(panelCabezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelArchivoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelArchivoEntradaTrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addComponent(jPanelCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelEntrada.add(panelCabeza, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 60));

        labelEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IMAGENENTRADA2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addComponent(labelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelEntrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 550, Short.MAX_VALUE)
        );

        panelEntrada.add(jPanelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 1030, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
      ShowPanel(home);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        btnHome.setBackground(new Color(87,113,128));
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        btnHome.setBackground(new Color(82,129,137));
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnEmpezarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpezarMouseClicked
        SwingUtilities.invokeLater(() -> {
        PanelDibujo panelDibujo = Principal.getInstance().getPanelDibujo();
        
        
        if (panelDibujo.getFiguras().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay figuras para graficar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        JFrame frame = new JFrame("Figuras Graficadas");
        JScrollPane scrollPane = new JScrollPane(panelDibujo);
        frame.add(scrollPane, BorderLayout.CENTER);

        // Crear botones de zoom
        JButton btnZoomIn = new JButton("Zoom In");
        btnZoomIn.addActionListener(e -> {
            panelDibujo.setScaleFactor(panelDibujo.getScaleFactor() * 1.1);
        });

        JButton btnZoomOut = new JButton("Zoom Out");
        btnZoomOut.addActionListener(e -> {
            panelDibujo.setScaleFactor(panelDibujo.getScaleFactor() / 1.1);
        });

        // Crear un panel para los botones de control
        JPanel controlPanel = new JPanel();
        controlPanel.add(btnZoomIn);
        controlPanel.add(btnZoomOut);
        
        // Añadir el panel de control en la parte inferior
        frame.add(controlPanel, BorderLayout.SOUTH);

        // Configurar la ventana
        frame.setSize(800, 800);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setVisible(true);

        System.out.println("Graficando figuras...");
        System.out.println("Figuras graficadas.");
    });
    }//GEN-LAST:event_btnEmpezarMouseClicked

    private void btnEmpezarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpezarMouseEntered
        btnEmpezar.setBackground(new Color(87,113,128));
    }//GEN-LAST:event_btnEmpezarMouseEntered

    private void btnEmpezarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpezarMouseExited
        btnEmpezar.setBackground(new Color(82,129,137));
    }//GEN-LAST:event_btnEmpezarMouseExited

    private void btnReporteOperacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteOperacionMouseClicked
        PanelDibujo panelDibujo = Principal.getInstance().getPanelDibujo();
        
        
        if (panelDibujo.getFiguras().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay reportes para mostrar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ShowPanel(Principal.getInstance().getPanelReportes());
    }//GEN-LAST:event_btnReporteOperacionMouseClicked

    private void btnReporteOperacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteOperacionMouseEntered
        btnReporteOperacion.setBackground(new Color(87,113,128));
    }//GEN-LAST:event_btnReporteOperacionMouseEntered

    private void btnReporteOperacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteOperacionMouseExited
         btnReporteOperacion.setBackground(new Color(82,129,137));
    }//GEN-LAST:event_btnReporteOperacionMouseExited

    private void panelCabezaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCabezaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelCabezaMousePressed

    private void panelCabezaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCabezaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelCabezaMouseDragged

    private void jLabelArchivoEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelArchivoEntradaMouseClicked
        // cargarArchivoEntrada();
    }//GEN-LAST:event_jLabelArchivoEntradaMouseClicked

    private void jPanelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseExited
        jPanelCerrar.setBackground(Color.white);
    }//GEN-LAST:event_jPanelCerrarMouseExited

    private void jPanelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseEntered
        jPanelCerrar.setBackground(Color.red);
    }//GEN-LAST:event_jPanelCerrarMouseEntered

    private void jPanelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jPanelCerrarMouseClicked

    private void btnErroresLSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnErroresLSMouseClicked
        ShowPanel(Principal.getInstance().getPanelErrores());
    }//GEN-LAST:event_btnErroresLSMouseClicked

    private void btnErroresLSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnErroresLSMouseEntered
        btnErroresLS.setBackground(new Color(87,113,128));
    }//GEN-LAST:event_btnErroresLSMouseEntered

    private void btnErroresLSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnErroresLSMouseExited
         btnErroresLS.setBackground(new Color(82,129,137));
    }//GEN-LAST:event_btnErroresLSMouseExited

    public PanelDibujo getPanelDibujo() {
        return panelDibujo;
    }

    
    private void ShowPanel(JPanel panel){
        panel.setSize(1040, 600);
        panel.setLocation(0, 0);

        jPanelContent.removeAll();
        jPanelContent.setLayout(new BorderLayout());
        jPanelContent.add(panel, BorderLayout.CENTER);
        jPanelContent.revalidate();
        jPanelContent.repaint();
      }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelExit;
    private javax.swing.JPanel btnEmpezar;
    private javax.swing.JPanel btnErroresLS;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnReporteOperacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelArchivoEntrada;
    private javax.swing.JLabel jLabelArchivoEntradaTrafico;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelStart;
    private javax.swing.JLabel jLabelStart1;
    private javax.swing.JLabel jLabelStart2;
    private javax.swing.JPanel jPanelCerrar;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JLabel jlabelICONO;
    private javax.swing.JPanel jpanelMenu;
    private javax.swing.JLabel labelEntrada;
    private javax.swing.JPanel panelCabeza;
    private javax.swing.JPanel panelEntrada;
    // End of variables declaration//GEN-END:variables
}
