
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.geometric.analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LINEA = 11;
  public static final int MENOS = 19;
  public static final int MULTIPLICACION = 20;
  public static final int DECIMAL = 4;
  public static final int DIVISION = 21;
  public static final int PAR_C = 17;
  public static final int CUADRADO = 8;
  public static final int UMENOS = 22;
  public static final int PAR_A = 16;
  public static final int VERDE = 15;
  public static final int ID = 2;
  public static final int ROJO = 13;
  public static final int GRAFICAR = 6;
  public static final int AMARILLO = 14;
  public static final int COMA = 5;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int POLIGONO = 9;
  public static final int CIRCULO = 7;
  public static final int AZUL = 12;
  public static final int ENTERO = 3;
  public static final int MAS = 18;
  public static final int RECTANGULO = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "ENTERO",
  "DECIMAL",
  "COMA",
  "GRAFICAR",
  "CIRCULO",
  "CUADRADO",
  "POLIGONO",
  "RECTANGULO",
  "LINEA",
  "AZUL",
  "ROJO",
  "AMARILLO",
  "VERDE",
  "PAR_A",
  "PAR_C",
  "MAS",
  "MENOS",
  "MULTIPLICACION",
  "DIVISION",
  "UMENOS"
  };
}

